# Test playbook
---
- hosts: all
  become: true
  roles:
    - role: role_under_test
      openio_users_add:
        - username: openio
          uid: 120
          name: openio account
          group: openio
          groups: []
          home_create: true

        - username: test
          name: John Doe
          uid: 2000
          password: "{{ 'my_password' | password_hash('sha512') }}"
          group: openio
          groups:
            - users
            - video
          append: false
          home_mode: "0750"
          home_create: true
          system: true
          authorized_keys:
            - "ssh-rsa my_key cedric@openio.io"
            - "{{ lookup('file', playbook_dir ~ '/id_rsa.pub') }}"
          authorized_keys_exclusive: true
          ssh_key_type: rsa
          ssh_key_bits: 2048
          ssh_key_password: "openio"
          ssh_key_generate: true
          #ssh_key: "{{ lookup('file', playbook_dir ~ '/id_rsa') }}"
          shell: /bin/sh
          update_password: on_create
      openio_users_ssh_key_type: rsa
      openio_users_ssh_key_bits: 2048
      openio_users_authorized_keys_exclusive: false

      # secondary groups
      openio_users_groups:
        - groupname: openio
          gid: 220
        - groupname: users
        - groupname: video
...
